# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven

name: Release to Maven Central

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name: Install GPG Private Key
        run: echo -e "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Publish package
        run: mvn --no-transfer-progress -B deploy -P package,sign,ossrh
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
