# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-java-packages-with-maven

name: Release to GitHub

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github

      - name: Install GPG Private Key
        run: echo -e "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --batch --import

      - name: Release
        run: mvn --no-transfer-progress -B deploy -P package,sign
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Prepare artifacts
        run: mkdir staging && cp target/*.jar staging && cp target/*.tar.gz staging
      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Extract tar.gz name
        id: extract_tar_name
        run: |
          ARTIFACT_NAME=$(basename staging/*.tar.gz)
          echo "::set-output name=artifact_name::$ARTIFACT_NAME"
      - name: Upload tar.gz
        id: upload_tar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: staging/${{ steps.extract_tar_name.outputs.artifact_name }}
          asset_name: ${{ steps.extract_tar_name.outputs.artifact_name }}
          asset_content_type: application/tar+gzip
