# This workflow will build a Java project with Maven
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

name: Build

on:
  push:
    branches: [ master ]
  pull_request_target:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode --no-transfer-progress --update-snapshots package -P package

      - name: Prepare artifacts
        run: mkdir staging && cp target/*.jar staging && cp target/*.tar.gz staging
      - name: Archive artifacts
        uses: actions/upload-artifact@v1
        with:
          name: Package
          path: staging
